// Generated by skills/kotoba-idle-spritemap/scripts/build_idle_spritemap.py.
// Do not edit by hand; update the generator and rerun it.

import CoreGraphics
import Foundation

struct KotobaCompanionIdleFrame: Equatable {
    let matrix: [String]
    let duration: TimeInterval
    let yOffsetRatio: CGFloat
}

enum KotobaCompanionIdleSpritemap {
    static let cycleDuration: TimeInterval = 2.50

    static let reducedMotionYOffsetRatio: CGFloat = -0.018

    static func frames(for stage: KotobaCompanionStage) -> [KotobaCompanionIdleFrame] {
        switch stage {
        case .newborn: Self.newbornFrames
        case .traveler: Self.travelerFrames
        case .guardian: Self.guardianFrames
        }
    }

    static func still(for stage: KotobaCompanionStage) -> [String] {
        frames(for: stage)[0].matrix
    }

    static func frame(for stage: KotobaCompanionStage, elapsed: TimeInterval) -> KotobaCompanionIdleFrame {
        let stageFrames = frames(for: stage)
        let cycleTime = elapsed.truncatingRemainder(dividingBy: cycleDuration)
        let normalizedTime = cycleTime >= 0 ? cycleTime : cycleTime + cycleDuration
        var cursor: TimeInterval = 0

        for frame in stageFrames {
            cursor += frame.duration
            if normalizedTime < cursor {
                return frame
            }
        }

        return stageFrames[0]
    }

    private static let newbornFrames: [KotobaCompanionIdleFrame] = [
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBRBBOOBBRBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.32,
            yOffsetRatio: 0.010
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBRBOOBRBBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.20,
            yOffsetRatio: -0.012
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBRBOOBRBBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.24,
            yOffsetRatio: -0.036
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBKKBBKKBO.",
                ".OBBBBBBBBO.",
                "OBBRBOOBRBBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.10,
            yOffsetRatio: -0.040
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBRBOOBRBBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.22,
            yOffsetRatio: -0.030
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBRBBOOBBRBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 0.28,
            yOffsetRatio: -0.006
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBRBBOOBBRBO",
                "OBBBBBBBBBBO",
                ".OBBBBBBBBO.",
                ".OBBBBBBBBO.",
                "..OBBOOBBO..",
                "...OBO.OBO..",
                "....O...O...",
            ],
            duration: 1.14,
            yOffsetRatio: 0.014
        )
    ]

    private static let travelerFrames: [KotobaCompanionIdleFrame] = [
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "..OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.32,
            yOffsetRatio: 0.010
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "..OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.20,
            yOffsetRatio: -0.012
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "..OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.24,
            yOffsetRatio: -0.036
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBKKBBKKBO.",
                ".OBBBBBBBBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "..OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.10,
            yOffsetRatio: -0.040
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "..OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.22,
            yOffsetRatio: -0.030
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "..OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.28,
            yOffsetRatio: -0.006
        ),
        .init(
            matrix: [
                "....OOOO....",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OBBBBBBBBO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "..OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 1.14,
            yOffsetRatio: 0.014
        )
    ]

    private static let guardianFrames: [KotobaCompanionIdleFrame] = [
        .init(
            matrix: [
                ".G..OOOO..G.",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "G.OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.32,
            yOffsetRatio: 0.010
        ),
        .init(
            matrix: [
                "..G.OOOO.G..",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "G.OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.20,
            yOffsetRatio: -0.012
        ),
        .init(
            matrix: [
                "..G.OOOO.G..",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "G.OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.24,
            yOffsetRatio: -0.036
        ),
        .init(
            matrix: [
                "..G.OOOO.G..",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBKKBBKKBO.",
                ".OBBBBBBBBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "G.OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.10,
            yOffsetRatio: -0.040
        ),
        .init(
            matrix: [
                "..G.OOOO.G..",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDSSSO.",
                "G.OBBOOSSO..",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.22,
            yOffsetRatio: -0.030
        ),
        .init(
            matrix: [
                ".G..OOOO..G.",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "G.OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 0.28,
            yOffsetRatio: -0.006
        ),
        .init(
            matrix: [
                ".G..OOOO..G.",
                "..OOBBBBOO..",
                ".OBBLBLBBBO.",
                ".OGGGGGGGGO.",
                ".OBWWBBWWBO.",
                ".OBWKBBWKBO.",
                "OBBBBOOBBBBO",
                "OBBBBBBBBBBO",
                ".OSSSSSSSSO.",
                ".OSSDDDDSSO.",
                "G.OBBOOBSSO.",
                "...OBO.OSO..",
                "....O...O...",
            ],
            duration: 1.14,
            yOffsetRatio: 0.014
        )
    ]
}
