#!/usr/bin/env python3
from __future__ import annotations

import argparse
import difflib
import sys
from dataclasses import dataclass
from pathlib import Path


REPO_ROOT = Path(__file__).resolve().parents[3]
DEFAULT_OUTPUT = REPO_ROOT / "Packages/KotobaDesignSystem/Sources/KotobaDesignSystem/Components/RPG/KotobaCompanionIdleSpritemap.swift"
ALLOWED_SYMBOLS = set(".OBLWKSDGR")

BASE_MATRICES = {
    "newborn": [
        "....OOOO....", "..OOBBBBOO..", ".OBBLBLBBBO.", ".OBBBBBBBBO.",
        ".OBWWBBWWBO.", ".OBWKBBWKBO.", "OBRBBOOBBRBO", "OBBBBBBBBBBO",
        ".OBBBBBBBBO.", ".OBBBBBBBBO.", "..OBBOOBBO..", "...OBO.OBO..", "....O...O..."
    ],
    "traveler": [
        "....OOOO....", "..OOBBBBOO..", ".OBBLBLBBBO.", ".OBBBBBBBBO.",
        ".OBWWBBWWBO.", ".OBWKBBWKBO.", "OBBBBOOBBBBO", "OBBBBBBBBBBO",
        ".OSSSSSSSSO.", ".OSSDDDDSSO.", "..OBBOOBSSO.", "...OBO.OSO..", "....O...O..."
    ],
    "guardian": [
        ".G..OOOO..G.", "..OOBBBBOO..", ".OBBLBLBBBO.", ".OGGGGGGGGO.",
        ".OBWWBBWWBO.", ".OBWKBBWKBO.", "OBBBBOOBBBBO", "OBBBBBBBBBBO",
        ".OSSSSSSSSO.", ".OSSDDDDSSO.", "G.OBBOOBSSO.", "...OBO.OSO..", "....O...O..."
    ],
}


@dataclass(frozen=True)
class Frame:
    matrix: list[str]
    duration: float
    y_offset_ratio: float


def blink(matrix: list[str]) -> list[str]:
    frame = list(matrix)
    frame[4] = ".OBKKBBKKBO."
    frame[5] = ".OBBBBBBBBO."
    return frame


def sway(stage: str, matrix: list[str]) -> list[str]:
    frame = list(matrix)
    if stage == "newborn":
        frame[6] = "OBBRBOOBRBBO"
    elif stage == "traveler":
        frame[9] = ".OSSDDDSSSO."
        frame[10] = "..OBBOOSSO.."
    elif stage == "guardian":
        frame[0] = "..G.OOOO.G.."
        frame[9] = ".OSSDDDSSSO."
        frame[10] = "G.OBBOOSSO.."
    return frame


def frames_for(stage: str) -> list[Frame]:
    base = BASE_MATRICES[stage]
    lifted = sway(stage, base)
    return [
        Frame(base, 0.32, 0.0),
        Frame(lifted, 0.20, 0.0),
        Frame(lifted, 0.24, 0.0),
        Frame(blink(lifted), 0.10, 0.0),
        Frame(lifted, 0.22, 0.0),
        Frame(base, 0.28, 0.0),
        Frame(base, 1.14, 0.0),
    ]


def validate_frames(stage_frames: dict[str, list[Frame]]) -> None:
    for stage, frames in stage_frames.items():
        if not frames:
            raise ValueError(f"{stage} has no frames")

        rows = len(frames[0].matrix)
        cols = len(frames[0].matrix[0])
        if (rows, cols) != (13, 12):
            raise ValueError(f"{stage} must stay 13 rows x 12 columns, got {rows}x{cols}")

        for index, frame in enumerate(frames):
            if frame.duration <= 0:
                raise ValueError(f"{stage} frame {index} duration must be positive")
            if len(frame.matrix) != rows:
                raise ValueError(f"{stage} frame {index} row count changed")
            for row in frame.matrix:
                if len(row) != cols:
                    raise ValueError(f"{stage} frame {index} row width changed: {row}")
                unknown = set(row) - ALLOWED_SYMBOLS
                if unknown:
                    raise ValueError(f"{stage} frame {index} uses unknown symbols: {sorted(unknown)}")


def swift_string_list(rows: list[str], indent: str = "                ") -> str:
    return "\n".join(f'{indent}"{row}",' for row in rows)


def swift_frame(frame: Frame) -> str:
    matrix = swift_string_list(frame.matrix)
    return (
        "        .init(\n"
        "            matrix: [\n"
        f"{matrix}\n"
        "            ],\n"
        f"            duration: {frame.duration:.2f},\n"
        f"            yOffsetRatio: {frame.y_offset_ratio:.3f}\n"
        "        )"
    )


def render_swift(stage_frames: dict[str, list[Frame]]) -> str:
    cycle_duration = sum(frame.duration for frame in next(iter(stage_frames.values())))
    arrays = []

    for stage, frames in stage_frames.items():
        frame_source = ",\n".join(swift_frame(frame) for frame in frames)
        arrays.append(
            f"    private static let {stage}Frames: [KotobaCompanionIdleFrame] = [\n"
            f"{frame_source}\n"
            "    ]"
        )

    array_source = "\n\n".join(arrays)
    return (
        "// Generated by skills/kotoba-idle-spritemap/scripts/build_idle_spritemap.py.\n"
        "// Do not edit by hand; update the generator and rerun it.\n\n"
        "import CoreGraphics\n"
        "import Foundation\n\n"
        "struct KotobaCompanionIdleFrame: Equatable {\n"
        "    let matrix: [String]\n"
        "    let duration: TimeInterval\n"
        "    let yOffsetRatio: CGFloat\n"
        "}\n\n"
        "enum KotobaCompanionIdleSpritemap {\n"
        f"    static let cycleDuration: TimeInterval = {cycle_duration:.2f}\n\n"
        "    static let breathingRestYOffsetRatio: CGFloat = -0.012\n"
        "    static let breathingAmplitudeRatio: CGFloat = 0.030\n"
        "    static let reducedMotionYOffsetRatio: CGFloat = -0.018\n\n"
        "    static func frames(for stage: KotobaCompanionStage) -> [KotobaCompanionIdleFrame] {\n"
        "        switch stage {\n"
        "        case .newborn: Self.newbornFrames\n"
        "        case .traveler: Self.travelerFrames\n"
        "        case .guardian: Self.guardianFrames\n"
        "        }\n"
        "    }\n\n"
        "    static func still(for stage: KotobaCompanionStage) -> [String] {\n"
        "        frames(for: stage)[0].matrix\n"
        "    }\n\n"
        "    static func frame(for stage: KotobaCompanionStage, elapsed: TimeInterval) -> KotobaCompanionIdleFrame {\n"
        "        let stageFrames = frames(for: stage)\n"
        "        let cycleTime = elapsed.truncatingRemainder(dividingBy: cycleDuration)\n"
        "        let normalizedTime = cycleTime >= 0 ? cycleTime : cycleTime + cycleDuration\n"
        "        var cursor: TimeInterval = 0\n\n"
        "        for frame in stageFrames {\n"
        "            cursor += frame.duration\n"
        "            if normalizedTime < cursor {\n"
        "                return frame\n"
        "            }\n"
        "        }\n\n"
        "        return stageFrames[0]\n"
        "    }\n\n"
        f"{array_source}\n"
        "}\n"
    )


def write_or_check(output: Path, contents: str, check: bool) -> int:
    if check:
        current = output.read_text() if output.exists() else ""
        if current == contents:
            print(f"{output} is current")
            return 0
        diff = difflib.unified_diff(
            current.splitlines(keepends=True),
            contents.splitlines(keepends=True),
            fromfile=str(output),
            tofile=f"{output} (generated)",
        )
        sys.stdout.writelines(diff)
        return 1

    output.parent.mkdir(parents=True, exist_ok=True)
    output.write_text(contents)
    print(f"Wrote {output}")
    return 0


def main() -> int:
    parser = argparse.ArgumentParser(description="Generate Kotoba companion idle spritemap Swift data.")
    parser.add_argument("--output", type=Path, default=DEFAULT_OUTPUT)
    parser.add_argument("--check", action="store_true", help="Fail if the output file is not current.")
    args = parser.parse_args()

    stage_frames = {stage: frames_for(stage) for stage in ("newborn", "traveler", "guardian")}
    validate_frames(stage_frames)
    return write_or_check(args.output, render_swift(stage_frames), args.check)


if __name__ == "__main__":
    raise SystemExit(main())
